// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://dpzmm32j7vcopbcgywqcxajqbq.appsync-api.us-east-2.amazonaws.com/graphql",
      region: "us-east-2",
      defaultAuthMode: "apiKey",
      apiKey: "da2-xzblgjhxfvbenj6gpafw6uh77a",
    },
  },
};

export default config;
