export interface ChecklistQuestion {
  id: number;
  qcp: string;
  question: string;
  type: "boolean";
  promptOnFalse: string | null;
  promptOnTrue: string | null;
  value: boolean | null;
}

export const checklistQuestions: ChecklistQuestion[] = [
  {
    id: 1,
    qcp: "QCP - NA",
    question: "I have the GA Drawings for the scale",
    type: "boolean",
    promptOnFalse: "Request GA from Config",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 2,
    qcp: "QCP - NA",
    question: "I have the Delivery Note",
    type: "boolean",
    promptOnFalse: "Request Delivery note from supervisory controller",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 3,
    qcp: "QCP - 1",
    question: "I have completed my RA",
    type: "boolean",
    promptOnFalse: "RA Required for work",
    promptOnTrue: "Upload photo of RA",
    value: null,
  },
  {
    id: 4,
    qcp: "QCP - 2",
    question: "I have Isolated my belt",
    type: "boolean",
    promptOnFalse: "Isolation required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 5,
    qcp: "Install Step",
    question:
      "My Installation area meets all installation requirements as per the OEM Technical manual",
    type: "boolean",
    promptOnFalse: "Engage Product engineer",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 6,
    qcp: "QCP - 3",
    question: "Lift counterbalance and secure",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: "Verify against drawing then continue",
    value: null,
  },
  {
    id: 7,
    qcp: "QCP - 4",
    question: "Lift/remove belt over installation area",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: "Verify against drawing then continue",
    value: null,
  },
  {
    id: 8,
    qcp: "QCP - 5",
    question:
      "My installation area has been cleared of all existing Idlers and Obstructions",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 9,
    qcp: "QCP - 6",
    question: 'I have "dry fitted" all my components',
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: "Hold Point — Site supervisor and customer to sign",
    value: null,
  },
  {
    id: 10,
    qcp: "Install Step",
    question:
      "All Stringer joints in my Scale area has been Welded to prevent movement",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 11,
    qcp: "Install Step",
    question: "I have Run my Center Fishline",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 12,
    qcp: "Install Step",
    question: "I have mechanically installed and Leveled my scale",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 13,
    qcp: "Install Step",
    question: "I have shimmed my scale",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 14,
    qcp: "Install Step",
    question:
      "I have double checked my scale, alignment, height and level of my scale",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 15,
    qcp: "Install Step",
    question: "I have installed and Aligned my +3 and -3 Idlersets",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 16,
    qcp: "Install Step",
    question: "I have leveled and shimmed my +3 and -3 Idlersets",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 17,
    qcp: "Install Step",
    question: "I have run my Installation Reference Lines",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 18,
    qcp: "Install Step",
    question: "I have Installed and Aligned my +1, +2, -1 & -2 Idler sets",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 19,
    qcp: "Install Step",
    question: "I have Leveled and shimmed my +1, +2, -1 & -2 Idler sets",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 20,
    qcp: "QCP - 7",
    question: "I have re-checked my entire Installation",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 21,
    qcp: "Install Step",
    question: "I have Installed my EMCBS Panel",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 22,
    qcp: "QCP - 8",
    question: "I have lowered the conveyor belt back onto the scale",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: "Verify against drawing then continue",
    value: null,
  },
  {
    id: 23,
    qcp: "QCP - 9",
    question: "The conveyor belt has been re-tensioned",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
  {
    id: 24,
    qcp: "QCP - 10",
    question:
      "My belt tracking is running straight and even throughout the whole belt rotation",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: "Hold Point — Site supervisor and customer to sign",
    value: null,
  },
  {
    id: 25,
    qcp: "QCP - 11",
    question: "There are no obstructions / Hold points",
    type: "boolean",
    promptOnFalse: "Action required",
    promptOnTrue: null,
    value: null,
  },
];